//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfCreator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class DepartmentPdf : global::System.Configuration.ApplicationSettingsBase {
        
        private static DepartmentPdf defaultInstance = ((DepartmentPdf)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DepartmentPdf())));
        
        public static DepartmentPdf Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>This telephone directory is generated nightly using data taken from the Ba" +
            "nner </string>\r\n  <string>system. Some of the basic directory data starting on p" +
            "age 11 can be changed </string>\r\n  <string>using Self Service on Trailhead. More" +
            " information is available at </string>\r\n  <string>http://inside.mines.edu/Direct" +
            "oryServicesDataSources . To update information </string>\r\n  <string>in pages 1-1" +
            "1, please contact Telecom at https://www.mines.edu/ccit/telecommunications/ . Fo" +
            "r department/name/title or </string>\r\n  <string>other assignment-related changes" +
            ", please contact the HR department </string>\r\n  <string>(https://www.mines.edu/h" +
            "umanresources/) .</string>\r\n  <string />\r\n  <string>The Colorado School of Mines" +
            " does not discriminate against individuals on the basis of age, sex, sexual orie" +
            "ntation, </string>\r\n  <string>gender identity, gender expression, race, religion" +
            ", ethnicity, national origin, </string>\r\n  <string>disability, military service," +
            " or genetic information in its administration of </string>\r\n  <string>educationa" +
            "l policies, programs, or activities; admissions policies; scholarship </string>\r" +
            "\n  <string>and loan programs; athletic or other school-administered programs; or" +
            " employment.</string>\r\n  <string />\r\n  <string>Additional information about acce" +
            "ss and equal opportunity, including the names </string>\r\n  <string>of staff memb" +
            "ers to whom inquiries regarding compliance may be directed, can </string>\r\n  <st" +
            "ring>be found at https://www.mines.edu/policy-library/. </string>\r\n</ArrayOfStri" +
            "ng>")]
        public global::System.Collections.Specialized.StringCollection Introduction {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Introduction"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Excel")]
        public string DataProvider {
            get {
                return ((string)(this["DataProvider"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TBD")]
        public string ServiceCallQuery {
            get {
                return ((string)(this["ServiceCallQuery"]));
            }
        }
    }
}
